/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/ScaryGuy.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions.Flap.play();
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[0, 0, Math.PI / 2]}>
        <primitive object={nodes.Bone} />
        <primitive object={nodes.Bone001} />
        <primitive object={nodes.Bone009} />
        <skinnedMesh geometry={nodes.Cube.geometry} material={materials.Material} skeleton={nodes.Cube.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/ScaryGuy.gltf')
